// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dwadmieuvqrqsdwexxfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR3YWRtaWV1dnFycXNkd2V4eGZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5NDQ5NTYsImV4cCI6MjA2MjUyMDk1Nn0.lTEJdYNvoaTHLeOtTfg6SkiHinvNAj67MGwpYA4Vchk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);